### ISSUE TITLE
Sketch Fails to Compile after Upgrade to Arduino IDE 3.2.3 

### ISSUE THREAD

**Issue by b-wave** [b-wave/VP2_TFT-Weather-Receiver#1]
After upgrading to IDE 3.2.3 from 1.8.19 the sketch will no longer compile.  I tried rolling back to 1.8.19 but gives the same error.  The last good compile on 07/26/2020 V1.13D was on the edge of memory limits but compiled just fine.  The last time i recorder memory usage it was using approximately:

 31220 bytes (98%) of program storage space. Maximum is 31744 bytes.
 Global variables use 931 bytes of dynamic memory. W/O DEBUG ENABLED

I don't see any DEBUG enabled.  I suspect since there are some multiple libraries found during the compile, there may be smaller versions not used.  If i find which ones work i will add the working libs to this repository. 

Multiple libraries were found for "EEPROM.h" 
Multiple libraries were found for "DavisRFM69.h" 

maybe there are some compiler options that got changed during the upgrade that affect both versions. 

ERROR MESSAGE: 
Sketch uses 33672 bytes (106%) of program storage space. Maximum is 31744 bytes.

Global variables use 941 bytes (45%) of dynamic memory, leaving 1107 bytes for local variables. Maximum is 2048 bytes.
Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board

Compilation error: text section exceeds available space in board

**Comment by b-wave** [comment]
Compiles fine with Arduino Mega or Mega2: 

Sketch uses 35584 bytes (14%) of program storage space. Maximum is 253952 bytes.

Global variables use 955 bytes (11%) of dynamic memory, leaving 7237 bytes for local variables. Maximum is 8192 bytes.
